# Aula 2 — Indicador de mulheres

Fonte: **Tabela 1.1.1.xls**, IBGE, PNAD Contínua 2022.

Para executar, deixe o notebook e a tabela na mesma pasta e execute as células em ordem. Caso necessário, instale as bibliotecas com `python -m pip install pandas xlrd`.

In [1]:

# No terminal, uma vez: python -m pip install xlrd pandas
import pandas as pd

In [2]:
# Deixe a tabela na mesma pasta deste notebook.
path = "Tabela 1.1.1.xls"

In [3]:
indicador_1 = pd.read_excel(path, engine="xlrd")

In [4]:
indicador_1

   Tabela 1.1.1 - Número médio de horas semanais dedicadas aos cuidados de pessoas e/ou afazeres domésticos das pessoas de 14 anos ou mais de idade, na semana de referência, por sexo e cor ou raça, segundo Grandes Regiões e Unidades da Federação - Brasil - 2022  ...      Unnamed: 7
0                                                 NaN                                                                                                                                                                                                                  ...             NaN
1                                                 NaN                                                                                                                                                                                                                  ...             NaN
2             Grandes Regiões e Unidades da Federação                                                                                                                                                                                                                  ...             NaN
3                                                 NaN                                                                                                                                                                                                                  ...             NaN
4                                                 NaN                                                                                                                                                                                                                  ...             NaN
5                                                 NaN                                                                                                                                                                                                                  ...             NaN
6                                                 NaN                                                                                                                                                                                                                  ...  Preta ou parda
7                                              Brasil                                                                                                                                                                                                                  ...       22.037998
8                                               Norte                                                                                                                                                                                                                  ...       20.534188
9                                            Rondônia                                                                                                                                                                                                                  ...        21.06141
10                                               Acre                                                                                                                                                                                                                  ...       16.710754
11                                           Amazonas                                                                                                                                                                                                                  ...       20.716986
12                                            Roraima                                                                                                                                                                                                                  ...       16.560244
13                                               Pará                                                                                                                                                                                                                  ...       21.591144
14                                              Amapá                                                                                                                                                                                                                  ...       15.908487
15                                          Tocantins                                                                                                                                                                                                                  ...       19.629399
16                                           Nordeste                                                                                                                                                                                                                  ...       23.716716
17                                           Maranhão                                                                                                                                                                                                                  ...       20.739589
18                                              Piauí                                                                                                                                                                                                                  ...        23.69544
19                                              Ceará                                                                                                                                                                                                                  ...       24.952274
20                                Rio Grande do Norte                                                                                                                                                                                                                  ...       24.422884
21                                            Paraíba                                                                                                                                                                                                                  ...        24.03565
22                                         Pernambuco                                                                                                                                                                                                                  ...       24.243396
23                                            Alagoas                                                                                                                                                                                                                  ...       25.856637
24                                            Sergipe                                                                                                                                                                                                                  ...       25.637681
25                                              Bahia                                                                                                                                                                                                                  ...       23.217119
26                                            Sudeste                                                                                                                                                                                                                  ...       21.990431
27                                       Minas Gerais                                                                                                                                                                                                                  ...       23.075751
28                                     Espírito Santo                                                                                                                                                                                                                  ...       22.196626
29                                     Rio de Janeiro                                                                                                                                                                                                                  ...       20.957728
30                                          São Paulo                                                                                                                                                                                                                  ...        21.76762
31                                                Sul                                                                                                                                                                                                                  ...       19.338734
32                                             Paraná                                                                                                                                                                                                                  ...        19.36538
33                                     Santa Catarina                                                                                                                                                                                                                  ...       19.646573
34                                  Rio Grande do Sul                                                                                                                                                                                                                  ...        19.10772
35                                       Centro-Oeste                                                                                                                                                                                                                  ...        19.33104
36                                 Mato Grosso do Sul                                                                                                                                                                                                                  ...       19.542761
37                                        Mato Grosso                                                                                                                                                                                                                  ...       18.695923
38                                              Goiás                                                                                                                                                                                                                  ...       19.587913
39                                   Distrito Federal                                                                                                                                                                                                                  ...       19.307332
40                                                NaN                                                                                                                                                                                                                  ...             NaN
41  Fonte: IBGE. Pesquisa Nacional por Amostra de ...                                                                                                                                                                                                                  ...             NaN
42                                             Notas:                                                                                                                                                                                                                  ...             NaN
43  (1) Calculado apenas para as pessoas que decla...                                                                                                                                                                                                                  ...             NaN
44  (2) Exclusive as pessoas sem declaração das ho...                                                                                                                                                                                                                  ...             NaN

[45 rows x 8 columns]

O `.xls` do IBGE mistura **título**, cabeçalho em várias linhas e **notas no rodapé**.  
Cortamos isso e deixamos só: **nomes das colunas + números**.

Tabela 1.1.1 - Número médio de horas semanais dedicadas aos cuidados de pessoas e/ou afazeres domésticos das pessoas de 14 anos ou mais de idade, na semana de referência, por sexo e cor ou raça, segundo Grandes Regiões e Unidades da Federação - Brasil - 2022

In [5]:
# Lê sem usar a 1ª linha como nome de coluna (senão o título vira "coluna")
bruto = pd.read_excel(path, engine="xlrd", header=None)

# Linhas 0–7: título/cabeçalho  |  8–40: resultados  |  41+: fonte e notas
indicador_1 = bruto.iloc[8:41].copy()
indicador_1.columns = [
    "uf_regiao",
    "total",
    "total_branca",
    "total_preta_parda",
    "homem_branca",
    "homem_preta_parda",
    "mulher_branca",
    "mulher_preta_parda",
]
indicador_1 = indicador_1.reset_index(drop=True)

# horas são número, não texto
for col in indicador_1.columns[1:]:
    indicador_1[col] = pd.to_numeric(indicador_1[col], errors="coerce")

indicador_1

              uf_regiao      total  ...  mulher_branca  mulher_preta_parda
0                Brasil  16.985781  ...      20.404106           22.037998
1                 Norte  16.187037  ...      19.295780           20.534188
2              Rondônia  17.014162  ...      20.412887           21.061410
3                  Acre  13.606903  ...      16.130352           16.710754
4              Amazonas  16.807290  ...      18.764969           20.716986
5               Roraima  13.639257  ...      16.135877           16.560244
6                  Pará  16.474268  ...      19.835110           21.591144
7                 Amapá  13.586656  ...      16.648579           15.908487
8             Tocantins  15.815781  ...      19.663713           19.629399
9              Nordeste  18.499396  ...      22.744666           23.716716
10             Maranhão  16.669614  ...      19.881056           20.739589
11                Piauí  17.960366  ...      20.494063           23.695440
12                Ceará  19.499293  ...      23.019718           24.952274
13  Rio Grande do Norte  18.307740  ...      23.547080           24.422884
14              Paraíba  18.920816  ...      23.642936           24.035650
15           Pernambuco  19.306249  ...      23.357880           24.243396
16              Alagoas  20.217129  ...      24.093655           25.856637
17              Sergipe  18.826541  ...      21.740902           25.637681
18                Bahia  17.849776  ...      22.572730           23.217119
19              Sudeste  17.104218  ...      20.732969           21.990431
20         Minas Gerais  17.502141  ...      22.186650           23.075751
21       Espírito Santo  17.111106  ...      20.464462           22.196626
22       Rio de Janeiro  16.716263  ...      19.203741           20.957728
23            São Paulo  17.071295  ...      20.771186           21.767620
24                  Sul  15.527769  ...      19.012969           19.338734
25               Paraná  15.390122  ...      18.896661           19.365380
26       Santa Catarina  16.039355  ...      19.414764           19.646573
27    Rio Grande do Sul  15.356709  ...      18.868230           19.107720
28         Centro-Oeste  15.000763  ...      18.220683           19.331040
29   Mato Grosso do Sul  15.309783  ...      18.593200           19.542761
30          Mato Grosso  14.239989  ...      17.782825           18.695923
31                Goiás  15.186471  ...      18.440842           19.587913
32     Distrito Federal  15.096351  ...      17.738123           19.307332

[33 rows x 8 columns]

In [6]:
# Média nacional = linha Brasil (dado do IBGE), não a média das linhas da tabela
media_nacional = indicador_1.loc[indicador_1["uf_regiao"] == "Brasil", "total"].item()
media_nacional

16.985780816563242

In [7]:
media_nacional

16.985780816563242

Qual(is) estado(s) está acima da média nacional de afazeres domésticos?

In [8]:
regioes = ["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"]

estados = indicador_1[~indicador_1["uf_regiao"].isin(["Brasil"] + regioes)]

acima_media = estados.loc[
    estados["total"] > media_nacional,
    ["uf_regiao", "total"],
].sort_values("total", ascending=False)

print(f"Média nacional (Brasil): {media_nacional:.2f} horas/semana")
print(f"Estados acima da média: {len(acima_media)}")
acima_media

Média nacional (Brasil): 16.99 horas/semana
Estados acima da média: 12

              uf_regiao      total
16              Alagoas  20.217129
12                Ceará  19.499293
15           Pernambuco  19.306249
14              Paraíba  18.920816
17              Sergipe  18.826541
13  Rio Grande do Norte  18.307740
11                Piauí  17.960366
18                Bahia  17.849776
20         Minas Gerais  17.502141
21       Espírito Santo  17.111106
23            São Paulo  17.071295
2              Rondônia  17.014162

Quais estados estão abaixo da média?

In [9]:
regioes = ["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"]

estados = indicador_1[~indicador_1["uf_regiao"].isin(["Brasil"] + regioes)]

abaixo_media = estados.loc[
    estados["total"] < media_nacional,
    ["uf_regiao", "total"],
].sort_values("total", ascending=False)

print(f"Média nacional (Brasil): {media_nacional:.2f} horas/semana")
print(f"Estados abaixo da média: {len(abaixo_media)}")
abaixo_media

Média nacional (Brasil): 16.99 horas/semana
Estados abaixo da média: 15

             uf_regiao      total
4             Amazonas  16.807290
22      Rio de Janeiro  16.716263
10            Maranhão  16.669614
6                 Pará  16.474268
26      Santa Catarina  16.039355
8            Tocantins  15.815781
25              Paraná  15.390122
27   Rio Grande do Sul  15.356709
29  Mato Grosso do Sul  15.309783
31               Goiás  15.186471
32    Distrito Federal  15.096351
30         Mato Grosso  14.239989
5              Roraima  13.639257
3                 Acre  13.606903
7                Amapá  13.586656

Qual é o percentual de diferença no Brasil que mulheres trabalham mais que homens em casa?

In [10]:

brasil = indicador_1.loc[indicador_1["uf_regiao"] == "Brasil"].iloc[0]

homem = (brasil["homem_branca"] + brasil["homem_preta_parda"]) / 2
mulher = (brasil["mulher_branca"] + brasil["mulher_preta_parda"]) / 2

# quanto % a mais as mulheres trabalham em relação aos homens
percentual = (mulher - homem) / homem * 100

print(f"Homens (média das cores):   {homem:.2f} h/semana")
print(f"Mulheres (média das cores): {mulher:.2f} h/semana")
print(f"Comparação das médias simples por cor ou raça: mulheres +{percentual:.1f}%.")
print("Essa média simples não representa o percentual nacional ponderado por população.")

# recorte por cor (a tabela traz isso de fato)
perc_branca = (brasil["mulher_branca"] / brasil["homem_branca"] - 1) * 100
perc_preta_parda = (brasil["mulher_preta_parda"] / brasil["homem_preta_parda"] - 1) * 100
print(f"Branca:        mulheres +{perc_branca:.1f}%")
print(f"Preta ou parda: mulheres +{perc_preta_parda:.1f}%")

Homens (média das cores):   11.73 h/semana
Mulheres (média das cores): 21.22 h/semana
Comparação das médias simples por cor ou raça: mulheres +81.0%.
Essa média simples não representa o percentual nacional ponderado por população.
Branca:        mulheres +74.3%
Preta ou parda: mulheres +87.6%

Agora responda (Com códigos):
TODAS AS RESPOSTAS DEVEM SER EM PERCENTUAL
- Quantas horas mulheres pretas trabalham a mais que mulheres brancas em Minas Gerais?
- Quantas horas mulheres pretas trabalham a mais que homens brancos no Brasil?
- Quantas horas mulheres pretas trabalham a mais que mulheres brancas no Amapá?
- Quantas horas mulheres pretas trabalham a mais que mulheres brancas no Rio Grande do Sul?
- Quantas horas mulheres pretas trabalham a mais que mulheres brancas por região["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"] ?
- Dentre os estados da região sudeste Quantas horas mulheres pretas trabalham a mais que mulheres brancas?
-

## Resolução dos exercícios

A tabela reúne **pessoas pretas ou pardas** na mesma categoria; não permite analisar somente pessoas pretas. Os cálculos abaixo usam esse agrupamento.

**Diferença percentual = (horas do grupo comparado − horas do grupo de referência) / horas do grupo de referência × 100.**

Resultado positivo indica mais horas; negativo indica menos horas. Os cálculos usam os valores originais, com arredondamento apenas na exibição.

### 1. Minas Gerais — mulheres pretas ou pardas em relação às mulheres brancas

In [11]:
dados = indicador_1.loc[indicador_1["uf_regiao"] == "Minas Gerais"].iloc[0]

mulheres_pretas_pardas = dados["mulher_preta_parda"]
referencia = dados["mulher_branca"]
percentual = (mulheres_pretas_pardas - referencia) / referencia * 100

print(f"Minas Gerais: {percentual:+.2f}%".replace(".", ","))

Minas Gerais: +4,01%

### 2. Brasil — mulheres pretas ou pardas em relação aos homens brancos

In [12]:
dados = indicador_1.loc[indicador_1["uf_regiao"] == "Brasil"].iloc[0]

mulheres_pretas_pardas = dados["mulher_preta_parda"]
referencia = dados["homem_branca"]
percentual = (mulheres_pretas_pardas - referencia) / referencia * 100

print(f"Brasil: {percentual:+.2f}%".replace(".", ","))

Brasil: +88,28%

### 3. Amapá — mulheres pretas ou pardas em relação às mulheres brancas

In [13]:
dados = indicador_1.loc[indicador_1["uf_regiao"] == "Amapá"].iloc[0]

mulheres_pretas_pardas = dados["mulher_preta_parda"]
referencia = dados["mulher_branca"]
percentual = (mulheres_pretas_pardas - referencia) / referencia * 100

print(f"Amapá: {percentual:+.2f}%".replace(".", ","))

Amapá: -4,45%

No Amapá, o sinal negativo significa que mulheres pretas ou pardas dedicam **menos horas**, em média, que mulheres brancas.

### 4. Rio Grande do Sul — mulheres pretas ou pardas em relação às mulheres brancas

In [14]:
dados = indicador_1.loc[indicador_1["uf_regiao"] == "Rio Grande do Sul"].iloc[0]

mulheres_pretas_pardas = dados["mulher_preta_parda"]
referencia = dados["mulher_branca"]
percentual = (mulheres_pretas_pardas - referencia) / referencia * 100

print(f"Rio Grande do Sul: {percentual:+.2f}%".replace(".", ","))

Rio Grande do Sul: +1,27%

### 5. Comparação por Grande Região

Usamos a linha de cada região fornecida pelo IBGE.

In [15]:
regioes = ["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"]

for regiao in regioes:
    dados = indicador_1.loc[indicador_1["uf_regiao"] == regiao].iloc[0]
    percentual = (dados["mulher_preta_parda"] - dados["mulher_branca"]) / dados["mulher_branca"] * 100
    print(f"{regiao}: {percentual:+.2f}%".replace(".", ","))

Norte: +6,42%
Nordeste: +4,27%
Sudeste: +6,07%
Sul: +1,71%
Centro-Oeste: +6,09%

### 6. Comparação em cada estado do Sudeste

In [16]:
estados_sudeste = ["Minas Gerais", "Espírito Santo", "Rio de Janeiro", "São Paulo"]

for estado in estados_sudeste:
    dados = indicador_1.loc[indicador_1["uf_regiao"] == estado].iloc[0]
    percentual = (dados["mulher_preta_parda"] - dados["mulher_branca"]) / dados["mulher_branca"] * 100
    print(f"{estado}: {percentual:+.2f}%".replace(".", ","))

Minas Gerais: +4,01%
Espírito Santo: +8,46%
Rio de Janeiro: +9,13%
São Paulo: +4,80%

## Gráfico — Atividade 2

Comparação das horas semanais de homens e mulheres nas cinco Grandes Regiões.

In [ ]:
%pip install matplotlib seaborn

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
regioes = ["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"]
reg = indicador_1[indicador_1["uf_regiao"].isin(regioes)].copy()
reg["homens"] = (reg["homem_branca"] + reg["homem_preta_parda"]) / 2
reg["mulheres"] = (reg["mulher_branca"] + reg["mulher_preta_parda"]) / 2

reg_long = reg.melt(
    id_vars="uf_regiao",
    value_vars=["homens", "mulheres"],
    var_name="sexo",
    value_name="horas",
)

fig, ax = plt.subplots(figsize=(9, 5))
sns.barplot(data=reg_long, x="uf_regiao", y="horas", hue="sexo", ax=ax)
ax.set_title("Afazeres domésticos por região e sexo")
ax.set_xlabel("Região")
ax.set_ylabel("Horas / semana")
plt.tight_layout()
plt.show()